name: Deploy prod

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS_PROD }}
      - name: Restart the application
        run: |
          ssh -p 22 root@65.108.90.129 "pushd /var/www/gour/services/messages-service && git fetch origin && git reset --hard origin/main && git pull && docker compose up --detach --build -d messages"
